# Generated by Django 4.0.2 on 2022-03-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_employee_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField(null=True)),
                ('services_provided', models.CharField(max_length=255)),
                ('company_long_description', models.TextField(null=True)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
            ],
        ),
    ]
